name: organimage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.7.3
  path: ^1.9.1
  forui: ^0.16.0
  photo_view: ^0.15.0
  reorderables: ^0.6.0
  file_picker: ^10.3.7
  cross_file: ^0.3.5+1
  desktop_drop: ^0.7.0
  path_provider: ^2.1.5
  window_manager: ^0.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true